# Generated by Django 5.2.4 on 2025-09-04 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_verificationcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='currency',
        ),
    ]
