# Generated by Django 5.2.4 on 2025-09-04 21:51

import django.db.models.deletion
import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0002_auto_20250904_2144'),
        ('users', '0003_remove_user_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='currency',
            field=models.ForeignKey(default=users.models.get_default_currency, on_delete=django.db.models.deletion.SET_DEFAULT, to='currency.currency'),
        ),
    ]
