# Generated by Django 5.2.4 on 2025-09-04 21:44

from django.db import migrations

def create_default_currency(apps, schema_editor):
    Currency = apps.get_model('currency', 'Currency')
    Currency.objects.get_or_create(
        code='USD',
        defaults={
            'name': "American Dollar",
            'conversion_rate': 1.0
        }
    )

class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_currency),
    ]
