# Generated by Django 5.2.4 on 2025-09-02 11:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Card',
            new_name='PaymentMethod',
        ),
        migrations.RenameModel(
            old_name='CardType',
            new_name='PaymentMethodType',
        ),
    ]
