# Generated by Django 5.2.4 on 2025-09-04 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomies', '0002_rename_card_paymentmethod_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='label',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='paymentmethod',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='paymentmethodtype',
            options={'ordering': ['type']},
        ),
    ]
